# Generated by Django 2.2.1 on 2019-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20190720_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='users_catgory', to='bot.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='users_content', to='bot.Content'),
        ),
    ]
