# Generated by Django 2.2.3 on 2019-07-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20190721_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_category', to='bot.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_content', to='bot.Content'),
        ),
    ]
