# Generated by Django 2.2.3 on 2019-07-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20190721_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_category',
            options={'verbose_name_plural': 'Категории пользователя'},
        ),
        migrations.AlterModelOptions(
            name='user_content',
            options={'verbose_name_plural': 'Контент пользователя'},
        ),
    ]
