# Generated by Django 2.2.3 on 2019-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20190721_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='link',
            name='image_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
