# Generated by Django 2.2.3 on 2019-07-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20190724_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='description',
            new_name='channel_description',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='channel_link',
        ),
    ]
