# Generated by Django 2.2.3 on 2019-07-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_link_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.RemoveField(
            model_name='content',
            name='code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='link',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
