# Generated by Django 2.2.3 on 2019-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20190727_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
    ]
