# Generated by Django 2.2.3 on 2019-08-01 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_auto_20190727_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='user_category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории пользователя'},
        ),
        migrations.AlterModelOptions(
            name='user_content',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контент пользователя'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название контента'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='link',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Content', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='link',
            name='image_link',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bot.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user_category',
            name='user_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='user_category',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.User', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user_content',
            name='user_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Content', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='user_content',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.User', verbose_name='Пользователь'),
        ),
    ]
