# Generated by Django 2.2.3 on 2019-08-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_auto_20190801_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Link', verbose_name='Канал')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рассылка каналов',
                'verbose_name_plural': 'Рассылка каналов',
            },
        ),
    ]
