# Generated by Django 2.2.3 on 2019-08-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_sentlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество переходов'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Ссылка'),
        ),
    ]
