# Generated by Django 2.2.3 on 2019-08-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20190803_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='clicks',
        ),
    ]
